export const SET_RESTAURANTS = 'SET_RESTAURANTS';
export const SET_RESTAURANT_DETAILS = 'SET_RESTAURANT_DETAILS';
export const SET_RESTAURANTS_ERROR = 'SET_RESTAURANTS_ERROR';
export const SET_RESTAURANT_DETAILS_ERROR = 'SET_RESTAURANT_DETAILS_ERROR';
export const START_LOADING = 'START_LOADING';
export const STOP_LOADING = 'STOP_LOADING';
